// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Fri Feb 25 16:56:43 2022

//  Module Declaration
module Ctrl_A
(
	// {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
	clk, p, clk_out, y
	// {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
);
// Port Declaration

	// {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	input clk;
	input [8:0] p;
	output clk_out;
	output [11:0] y;
	// {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

	wire clk_out;
	assign clk_out =! clk;
	reg [11:0] y;
	integer Counter = 0;
	
	
	always @(posedge clk) begin
											
					
					
					  	
						case (Counter)
										0: begin
										   //      109876543210 
										   y = 12'b000000000011; 
										   Counter = 1;
										   end
										
										1: begin
										   if (p[0] == 1) begin
														  //      109876543210 
													      y = 12'b000000000001;	   
														  Counter = 10;	   
													      end else begin
																   //      109876543210 
																   y = 12'b000000000100;
																   Counter = 2; 
																   end
																   
										   end
										   
										2: begin
										   //      109876543210 
										   y = 12'b000000000010; 
										   Counter = 3;
										   end
										   
										3: begin
										   
										   if (p[0] == 1) begin
														  //      109876543210 
													      y = 12'b000000000001;	   
														  Counter = 10;	   
													      end else begin
																   //      109876543210 
																   y = 12'b000000000100;
																   Counter = 4; 
																   end 
										   
										   end
										   
									    4: begin
										   
										   if (p[6] == 1) begin
														  //      109876543210 
													      y = 12'b100000000001;	   
														  Counter = 10;	   
													      end else begin
													      
																	if (p[7] == 1) begin
																					  //      109876543210 
																					  y = 12'b001000000000;	   
																					  Counter = 11;	   
																					  end else begin
																							   if (p[4] == 1) begin
																											  //      109876543210 
																											  y = 12'b000001000000;	   
																											  Counter = 5;	   
																											  end else begin
																												   //      109876543210 
																												   y = 12'b000000001000;
																												   Counter = 6; 
																												   end  
																							   end 
																    
																   end 
										   
										   end
										   
										   
										 5: begin
											//      109876543210
											y = 12'b000000001000;
											Counter = 6; 
											end
											
										6: begin
											if (p[3] == 0) begin
															
															if (p[4] == 0) begin
															//      109876543210 
															y = 12'b000000001000;	   
															Counter = 6;	   
															end else begin
															//      109876543210 
															y = 12'b000001000000;	   
															Counter = 5;
															end
																   
															end else begin
																		if (p[1] == 1) begin
																		//      109876543210 
																		y = 12'b000001100000;	   
																		Counter = 7;	   
																		end else begin
																				if (p[2] == 1) begin
																				//      109876543210 
																				y = 12'b000001110000;	   
																				Counter = 8;	   
																			    end else begin
																				
																						        if (p[8] == 0) begin
																								//      109876543210 
																								y = 12'b000010000000;	   
																								Counter = 9;	   
																								end else begin
																										 if (p[6] == 1) begin
																											//      109876543210 
																											y = 12'b100000000001;	   
																											Counter = 10;	   
																											end else begin
																													if (p[5] == 1) begin
																													//      109876543210 
																													y = 12'b001000000000;	   
																													Counter = 11;	   
																													end else begin
																													//      109876543210 
																													y = 12'b000000000000;	   
																													Counter = 10;	
																													end	
																											end
																								end	
																				end
																	end						  
															end 
											end
										
										7: begin
											
											if (p[2] == 1) begin
															//      009876543210 
															y = 12'b000001110000;	   
															Counter = 8;	   
															end else begin
															
																		if (p[8] == 0) begin
																		//      109876543210 
																		y = 12'b000010000000;	   
																		Counter = 9;	   
																		end else begin
																					if (p[6] == 1) begin
																					//      109876543210 
																					y = 12'b100000000001;	   
																					Counter = 10;	   
																					end else begin
																					
																								if (p[5] == 1) begin
																								//      109876543210 
																								y = 12'b001000000000;	   
																								Counter = 11;	   
																								end else begin
																								//      109876543210 
																								y = 12'b000000000000;	   
																								Counter = 10;
																								end
																					end
																		end
															
															
															
															end
											 
											end
											
										8: begin
											if (p[8] == 0) begin
											//      09876543210 
											y = 11'b00010000000;	   
											Counter = 9;	   
											end else begin
																if (p[6] == 1) begin
																//      109876543210 
																y = 12'b100000000001;	   
																Counter = 10;	   
																end else begin
																				if (p[5] == 1) begin
																				//      109876543210 
																				y = 12'b001000000000;	   
																				Counter = 11;	   
																				end else begin
																				//      109876543210 
																				y = 12'b000000000000;	   
																				Counter = 10;			
																				end
																							
																end		
											end
											
											end
											   
										9: begin
											if (p[6] == 1) begin
																//      109876543210 
																y = 12'b100000000001;	   
																Counter = 10;	   
																end else begin
																				if (p[5] == 1) begin
																				//      109876543210 
																				y = 12'b001000000000;	   
																				Counter = 11;	   
																				end else begin
																				//      109876543210 
																				y = 12'b000000000000;	   
																				Counter = 10;			
																				end
																							
																end 
											end  
										
										10: begin
											//      109876543210
											y = 12'b000100000000; 
											Counter = 11;
											
											end
											
										11: begin
											//      109876543210
											y = 12'b010000000000; 
											
											end
										
										  
										endcase;
							
						  end
	

endmodule
